# Project: suBoard_hid
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RES  = 
OBJ  = ./_objects/main.o ./_objects/suBoard.o ./_objects/hidwin.o $(RES)
LINKOBJ  = ./_objects/main.o ./_objects/suBoard.o ./_objects/hidwin.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -L"./hidLibrary" hidLibrary/setupapi.lib  -g3 
INCS =  -I"C:/Dev-Cpp/include"  -I"./hidLibrary"  -I"./suBoard" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"./hidLibrary"  -I"./suBoard" 
BIN  = suBoard_hid.exe
CXXFLAGS = $(CXXINCS)   -g3
CFLAGS = $(INCS)   -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before suBoard_hid.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "suBoard_hid.exe" $(LIBS)

./_objects/main.o: main.cpp
	$(CPP) -c main.cpp -o ./_objects/main.o $(CXXFLAGS)

./_objects/suBoard.o: suBoard/suBoard.c
	$(CPP) -c suBoard/suBoard.c -o ./_objects/suBoard.o $(CXXFLAGS)

./_objects/hidwin.o: hidLibrary/hidwin.cpp
	$(CPP) -c hidLibrary/hidwin.cpp -o ./_objects/hidwin.o $(CXXFLAGS)
